# Generated by Django 3.1.2 on 2020-11-17 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('policorp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
