# Generated by Django 3.1.2 on 2020-11-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policorp', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='Default', max_length=255),
            preserve_default=False,
        ),
    ]
