# Generated by Django 3.1.2 on 2020-11-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policorp', '0003_auto_20201119_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='availabiliy',
            new_name='availability',
        ),
    ]
