# Generated by Django 3.1.2 on 2020-11-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policorp', '0004_auto_20201119_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
