# Generated by Django 3.1.2 on 2020-11-17 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policorp', '0004_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='where',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='availableLocations', to='policorp.location'),
            preserve_default=False,
        ),
    ]
