# Generated by Django 3.1.2 on 2020-11-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policorp', '0006_booking_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
