# Generated by Django 3.1.2 on 2020-11-17 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policorp', '0006_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='what',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='availableTasks', to='policorp.task'),
            preserve_default=False,
        ),
    ]
