# Generated by Django 3.1.2 on 2020-11-23 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policorp', '0007_task_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1)),
        ),
    ]
