# Generated by Django 3.1.2 on 2020-11-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policorp', '0009_auto_20201123_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
