# Generated by Django 3.1.2 on 2020-11-26 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policorp', '0010_auto_20201123_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='supervisors',
            field=models.ManyToManyField(related_name='supervisedLocations', to=settings.AUTH_USER_MODEL),
        ),
    ]
