# Generated by Django 3.1.5 on 2021-01-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policorp', '0012_user_is_supervisor'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
