# Generated by Django 3.1.5 on 2021-04-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policorp', '0013_auto_20210130_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
