name: Testing
on:
  push:
    branches:
      - main
  schedule:
      - cron: '30 9 * * *'

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: pauh61syjzkx6$1d%euial5h&y-1=rlr39_z5e&g^7%!en)c$x
      DATABASE_PG_PASSWORD: poliuser
      DATABASE_PG_HOST: localhost
      DATABASE_PG_PORT: 5432

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      db:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_USER: poliuser
          POSTGRES_PASSWORD: poliuser
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        # Map port to the docker container image
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.5
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.8.5'
        # Optional - x64 or x86 architecture, defaults to x64
        architecture: 'x64'
    - name: Run Django tests
      run: |
        pip3 install --user django psycopg2
        python3 -m pip install coverage
        python3 manage.py collectstatic
        coverage run --source='.' manage.py test
        coverage html -d coverageReport --fail-under=90
    - name: Deploy report page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./coverageReport
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy on Heroku
      - uses: akhileshns/heroku-deploy@v3.9.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "poliapp"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          remote_branch: main
